"""
WinSecure Auto-Remediation Script Generator
Emits ready-to-run PowerShell remediation scripts (with rollback and
validation companions) from a scan's remediation actions.
"""
import os
import re
from typing import Any, Dict, List, Optional

from winsecure.models.scan import ScanResult
from winsecure.models.remediation import RemediationAction


class RemediationScriptGenerator:
    """Generates grouped, executable remediation script bundles to disk."""

    HEADER_TEMPLATE = """<#
.SYNOPSIS
    WinSecure Auto-Generated Remediation Script
.DESCRIPTION
    Remediation bundle for scan {scan_id} ({profile} profile, score {score}).
    Generated by WinSecure v{version} on {timestamp}.
.NOTES
    Review every script before execution. Run from an elevated PowerShell session.
#>

"""

    def __init__(self, output_dir: str):
        self.output_dir = output_dir

    # Characters Windows forbids in file names, plus trailing dots/spaces
    _UNSAFE_FILENAME_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')

    @classmethod
    def _safe_filename(cls, finding_id: str) -> str:
        """Strips characters Windows filenames cannot contain."""
        safe = cls._UNSAFE_FILENAME_CHARS.sub("_", finding_id).strip().rstrip(". ")
        return safe or "finding"

    def generate_bundle(
        self,
        result: ScanResult,
        actions: Optional[List[RemediationAction]] = None,
    ) -> Dict[str, Any]:
        """Writes remediation scripts for a scan; returns a manifest of emitted files."""
        if actions is None:
            actions = result.remediations
            if not actions and result.findings:
                # Compute remediations on the fly when the scan has none attached
                from winsecure.remediation.engine import RemediationEngine
                actions = RemediationEngine.generate_remediations(result.findings)

        scripts_dir = os.path.join(self.output_dir, "remediation_scripts")
        os.makedirs(scripts_dir, exist_ok=True)

        manifest: List[Dict[str, str]] = []
        header = self.HEADER_TEMPLATE.format(
            scan_id=result.scan_id,
            profile=result.profile,
            score=result.security_score,
            version=result.winsecure_version,
            timestamp=result.timestamp,
        )

        for action in actions:
            safe_id = self._safe_filename(action.finding_id)
            files = {
                "remediate": os.path.join(scripts_dir, f"{safe_id}_fix.ps1"),
                "rollback": os.path.join(scripts_dir, f"{safe_id}_rollback.ps1"),
                "validate": os.path.join(scripts_dir, f"{safe_id}_validate.ps1"),
            }

            self._write_script(files["remediate"], header + action.powershell_script)
            self._write_script(files["rollback"], header + action.rollback_guidance)
            self._write_script(
                files["validate"],
                header + (action.validation_command or "# Re-run: winsecure scan"),
            )

            manifest.append({
                "finding_id": action.finding_id,
                "title": action.title,
                "priority": action.priority.value,
                "requires_reboot": str(action.requires_reboot),
                "estimated_effort_minutes": str(action.estimated_effort_minutes),
                "files": files,
            })

        # Master run-all script executes fixes in priority order
        run_all_path = os.path.join(scripts_dir, "run_all_remediations.ps1")
        run_all_lines = [header]
        run_all_lines.append("# Execute all remediations in priority order.")
        run_all_lines.append("$ErrorActionPreference = 'Continue'\n")
        for entry in manifest:
            fix_file = os.path.basename(entry["files"]["remediate"])
            run_all_lines.append(f"Write-Host '==> Applying {entry['finding_id']}: {entry['title']}'")
            run_all_lines.append(f".\\{fix_file}")
        self._write_script(run_all_path, "\n".join(run_all_lines))

        return {
            "scripts_directory": scripts_dir,
            "script_count": len(manifest),
            "run_all_script": run_all_path,
            "manifest": manifest,
        }

    @staticmethod
    def _write_script(path: str, content: str) -> None:
        """Writes one script file with UTF-8 encoding."""
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content.rstrip() + "\n")
